# Generated by Django 4.0.4 on 2022-04-28 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='media/document')),
            ],
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=40)),
                ('Employe_id', models.CharField(max_length=40)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(max_length=20)),
                ('password', models.CharField(default='', max_length=60)),
                ('puch_in', models.TimeField(blank=True, null=True)),
                ('puch_out', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('logo', models.FileField(default='media/images/hrms.png', upload_to='media/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Priority', models.CharField(blank=True, max_length=40, null=True)),
                ('Project_leader', models.CharField(blank=True, max_length=60)),
                ('add_team1', models.CharField(max_length=40)),
                ('add_team2', models.CharField(max_length=40)),
                ('add_team3', models.CharField(max_length=40)),
                ('add_team4', models.CharField(max_length=40)),
                ('describe', models.TextField(max_length=300)),
                ('logo', models.FileField(default='media/document/python_assignment_5PHX6G6.pdf', upload_to='media/document/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('phone', models.CharField(max_length=40)),
                ('Employe_id', models.CharField(max_length=40)),
                ('role', models.CharField(max_length=20)),
                ('password', models.CharField(default='', max_length=60)),
                ('puch_in', models.TimeField(blank=True, null=True)),
                ('puch_out', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('logo', models.FileField(default='media/images/hrms.png', upload_to='media/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('checksum', models.CharField(blank=True, max_length=100, null=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='my_app.hr')),
            ],
        ),
        migrations.AddField(
            model_name='hr',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.user'),
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('phone', models.CharField(max_length=40)),
                ('date', models.DateField(null=True)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('salary', models.CharField(max_length=40, null=True)),
                ('password', models.CharField(max_length=60)),
                ('Employe_id', models.CharField(default='', max_length=40)),
                ('designation', models.CharField(max_length=50)),
                ('puch_in', models.TimeField(blank=True, null=True)),
                ('puch_out', models.TimeField(blank=True, null=True)),
                ('department', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('logo', models.FileField(default='media/images/hrms.png', upload_to='media/images/')),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.user')),
            ],
        ),
    ]
